import { useEffect, useState } from "react";
import { Activity, ArrowUpRight, AudioLines, Check, ChevronRight, CircleUserRound, LayoutDashboard, LogIn, LogOut, Menu, Moon, MoreHorizontal, PackageCheck, PanelLeftClose, PanelLeftOpen, Radio, Settings as SettingsIcon, ShieldCheck, Sparkles, UploadCloud, X } from "lucide-react";
import { api, authLink } from "./api";
import AmbientControl from "./AmbientControl";
import AdvancedConverter from "./AdvancedConverter";
import RobloxConverter from "./RobloxConverter";
import PublishWorkspace from "./PublishWorkspace";
import RobloxAccess from "./RobloxAccess";
import Settings from "./Settings";

const themes = ["cyan", "red", "yellow", "blue", "purple", "techno"];
const navItems = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "publish", label: "Publish assets", icon: UploadCloud }, { id: "converter", label: "Roblox converter", icon: Sparkles }, { id: "studio", label: "Audio studio", icon: AudioLines }, { id: "team", label: "Developer team", icon: CircleUserRound }, { id: "settings", label: "Settings", icon: SettingsIcon }];

export default function App() {
  const [page, setPage] = useState(getPageFromPath(window.location.pathname));
  const [collapsed, setCollapsed] = useState(false);
  const [user, setUser] = useState(null);
  const [config, setConfig] = useState(null);
  const [stats, setStats] = useState({ totalUsers: 0, totalUploads: 0, totalVisits: 0 });
  const [notice, setNotice] = useState(null);
  const [theme, setTheme] = useState(() => localStorage.getItem("zanexyuu-theme") || "cyan");
  const notify = (message, tone = "info") => { setNotice({ message, tone }); window.setTimeout(() => setNotice(null), 3200); };
  const refreshAuth = async () => { try { const data = await api("/api/auth/me"); setUser(data?.authenticated ? data.user : null); } catch { setUser(null); } };
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("zanexyuu-theme", theme); }, [theme]);
  useEffect(() => { const labels = { overview: "Overview", publish: "Publish assets", converter: "Roblox converter", studio: "Audio studio", team: "Developer team", settings: "Settings" }; const breadcrumb = document.querySelector(".breadcrumb b"); if (breadcrumb) breadcrumb.textContent = labels[page] || "Workspace"; }, [page]);
  useEffect(() => { Promise.all([refreshAuth(), api("/api/config").then(setConfig).catch(() => setConfig({ databaseReady: false })), api("/api/stats").then(setStats).catch(() => {})]); const params = new URLSearchParams(window.location.search); if (params.has("auth")) { const success = ["success", "roblox-connected", "discord-linked"].includes(params.get("auth")); window.history.replaceState({}, "", `${window.location.pathname}${window.location.hash}`); notify(success ? "Authentication connected successfully." : "Authentication needs attention.", success ? "success" : "error"); } }, []);
  useEffect(() => { const syncPage = () => setPage(getPageFromPath(window.location.pathname)); window.addEventListener("popstate", syncPage); return () => window.removeEventListener("popstate", syncPage); }, []);
  useEffect(() => {
    const refreshDashboard = () => { refreshAuth(); api("/api/stats").then(setStats).catch(() => {}); };
    const interval = window.setInterval(refreshDashboard, 30000);
    return () => window.clearInterval(interval);
  }, []);
  const go = target => { setPage(target); const paths = { overview: "/", publish: "/publish", converter: "/converter", studio: "/audio-studio", team: "/team", settings: "/settings" }; window.history.pushState({}, "", paths[target] || "/"); };
  const logout = async () => { try { await api("/api/auth/logout", { method: "POST" }); setUser(null); notify("You have been logged out."); } catch (error) { notify(error.message, "error"); } };

  function getPageFromPath(pathname) { if (pathname.includes("audio-studio")) return "studio"; if (pathname.includes("converter")) return "converter"; if (pathname.includes("publish")) return "publish"; if (pathname.includes("team")) return "team"; if (pathname.includes("settings")) return "settings"; return "overview"; }
  return <div className={`app-shell ${collapsed ? "is-collapsed" : ""}`}><Sidebar page={page} go={go} collapsed={collapsed} setCollapsed={setCollapsed} /><div className="app-content"><Topbar user={user} config={config} theme={theme} onTheme={() => setTheme(themes[(themes.indexOf(theme) + 1) % themes.length])} onLogout={logout} onMenu={() => setCollapsed(!collapsed)} /><main className="page-content">{page === "overview" && <Overview user={user} stats={stats} go={go} refreshAuth={refreshAuth} notify={notify} />}{page === "publish" && <PublishWorkspace user={user} notify={notify} />}{page === "converter" && <RobloxConverter notify={notify} />}{page === "studio" && <AdvancedConverter notify={notify} />}{page === "team" && <Team />}{page === "settings" && <Settings user={user} notify={notify} />}</main></div><MobileNav page={page} go={go} /><AmbientControl />{notice && <div className={`toast toast-${notice.tone}`}><span>{notice.tone === "success" ? <Check size={16} /> : <Activity size={16} />}</span>{notice.message}<button onClick={() => setNotice(null)}><X size={14} /></button></div>}</div>;
}

function Sidebar({ page, go, collapsed, setCollapsed }) { return <aside className="sidebar"><div className="sidebar-top"><a className="brand" href="/" onClick={event => { event.preventDefault(); go("overview"); }}><span className="brand-mark">Z</span><span className="brand-text"><b>ZANEXYUU</b><small>STUDIO</small></span></a><button className="icon-button sidebar-toggle" onClick={() => setCollapsed(!collapsed)} aria-label="Toggle navigation">{collapsed ? <PanelLeftOpen size={18} /> : <PanelLeftClose size={18} />}</button></div><div className="workspace-chip"><span className="live-dot" /><span><b>Roblox workspace</b><small>Secure asset tools</small></span></div><p className="nav-label">WORKSPACE</p><nav>{navItems.map(item => { const Icon = item.icon; return <button key={item.id} className={`nav-item ${page === item.id ? "is-active" : ""}`} onClick={() => go(item.id)}><Icon size={18} /><span>{item.label}</span>{page === item.id && <ChevronRight className="nav-arrow" size={15} />}</button>; })}</nav><div className="sidebar-bottom"><a className="help-card" href="https://discord.gg/pgsZDFTpWE" target="_blank" rel="noreferrer"><Sparkles size={17} /><span><b>Premium access</b><small>Remove upload limits</small></span><ArrowUpRight size={14} /></a><small className="version">ZANEXYUU © 2026. All rights reserved.</small></div></aside>; }

function MobileNav({ page, go }) { const items = [{ id: "overview", label: "Home", icon: LayoutDashboard }, { id: "publish", label: "Publish", icon: UploadCloud }, { id: "converter", label: "Converter", icon: Sparkles }, { id: "settings", label: "Settings", icon: SettingsIcon }]; return <nav className="mobile-nav" aria-label="Mobile navigation">{items.map(item => { const Icon = item.icon; return <button key={item.id} className={`mobile-nav-item ${page === item.id ? "is-active" : ""}`} onClick={() => go(item.id)} aria-current={page === item.id ? "page" : undefined}><Icon size={19} /><span>{item.label}</span></button>; })}</nav>; }

function Topbar({ user, config, theme, onTheme, onLogout, onMenu }) { const checkingService = config === null; const serviceUnavailable = config?.databaseReady === false; const serviceLabel = checkingService ? "Checking service..." : serviceUnavailable ? "Service unavailable" : "All systems operational"; return <header className="topbar"><button className="mobile-menu icon-button" onClick={onMenu}><Menu size={20} /></button><a className="topbar-brand" href="/" aria-label="Back to ZaneXyuu Studio home"><span className="brand-mark">Z</span></a><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14} /><b>{window.location.pathname.includes("audio-studio") ? "Audio studio" : window.location.pathname.includes("converter") ? "Roblox converter" : "Asset manager"}</b></div><div className="topbar-actions"><span className={`server-status ${serviceUnavailable || checkingService ? "is-offline" : ""}`}><i />{serviceLabel}</span><button className="icon-button theme-button" onClick={onTheme} title={`Accent: ${theme}`}><Moon size={17} /></button>{user ? <div className="profile-menu"><span className="avatar">{user.avatar ? <img src={user.avatar} alt="" /> : String(user.username || "U").charAt(0)}</span><span className="profile-copy"><b>{user.username}</b><small>{user.premium ? "Premium account" : "Free account"}</small></span>{user.provider === "google" && !user.discordLinked && !user.premium && <a className="connect-link" href={authLink("discord/link")}>Connect Discord</a>}<button className="icon-button"><MoreHorizontal size={17} /></button><button className="logout-button" onClick={onLogout} title="Log out"><LogOut size={16} /></button></div> : <span className="auth-links"><a className="button button-quiet button-small" href={authLink("google")}>Google</a><a className="button button-primary button-small" href={authLink("discord")}><LogIn size={16} />Sign in</a></span>}</div></header>; }

function Overview({ user, stats, go, refreshAuth, notify }) { return <div className="view-stack"><section className="welcome-row"><div><p className="eyebrow">{user ? `Good to see you, ${user.username}` : "WELCOME TO ZANEXYUU"}</p><h1>Your asset workspace<span>.</span></h1><p className="lead">Publish, prepare, and keep track of your Roblox development assets in one focused place.</p></div><div className="date-card"><span><Radio size={15} />SYSTEM STATUS</span><b>Online</b><small>{new Date().toLocaleDateString([], { weekday: "long", month: "short", day: "numeric" })}</small></div></section><section className="metric-grid"><Metric icon={CircleUserRound} label="Total users" value={stats.totalUsers} accent="blue" /><Metric icon={PackageCheck} label="Total uploads" value={stats.totalUploads} accent="mint" /><Metric icon={Activity} label="Total visits" value={stats.totalVisits} accent="orange" />{user && <Metric icon={ShieldCheck} label="Roblox access" value={user.robloxConnected ? "Ready" : "Setup"} accent={user.robloxConnected ? "mint" : "orange"} />}</section>{user && <QuotaPanel user={user} go={go} />}{!user && <section className="auth-banner"><div className="banner-icon"><ShieldCheck size={22} /></div><div><b>Sign in to unlock publishing</b><p>Connect Discord or Google to access your workspace and Roblox publishing tools.</p></div><div className="banner-actions"><a className="button button-primary" href={authLink("discord")}><LogIn size={16} />Discord</a><a className="button button-quiet" href={authLink("google")}>Google</a></div></section>}{user && <RobloxAccess user={user} onRefresh={refreshAuth} notify={notify} />}<section className="section-block"><SectionHeading eyebrow="QUICK ACTIONS" title="Choose your next move" /><div className="action-grid"><ActionCard icon={UploadCloud} title="Publish development item" copy="Send audio or animation files to Roblox." onClick={() => go("publish")} tone="blue" /><ActionCard icon={AudioLines} title="Audio converter" copy="Tune format, timing, and metadata." onClick={() => go("converter")} tone="orange" /><ActionCard icon={CircleUserRound} title="Meet the team" copy="See the people behind the workspace." onClick={() => go("team")} tone="mint" /></div></section><PremiumCard user={user} /></div>; }
function QuotaPanel({ user, go }) { const limit = Number(user.dailyLimit || 0); const used = Number(user.usedToday || 0); const remaining = user.premium ? null : Math.max(0, Number(user.remaining ?? limit - used)); const percent = user.premium || !limit ? 0 : Math.min(100, Math.round(used / limit * 100)); const reset = new Date(); reset.setHours(24, 0, 0, 0); const hours = Math.max(0, Math.floor((reset - Date.now()) / 3600000)); const minutes = Math.max(0, Math.floor((reset - Date.now()) / 60000) % 60); return <section className="quota-panel"><div><p className="eyebrow">DAILY PUBLISHING QUOTA</p><h2>{user.premium ? "Unlimited publishing" : `${used} / ${limit} files used`}</h2><p>{user.premium ? "Premium access is active for this workspace." : `${remaining} files remaining · resets in ${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m`}</p></div><span className={`pill ${user.premium ? "is-premium" : ""}`}>{user.premium ? "PREMIUM" : "FREE PLAN"}</span>{!user.premium && <div className="quota-track"><i style={{ width: `${percent}%` }} /></div>}<button className="button button-quiet button-small" onClick={() => go("publish")}>Open publish queue <ArrowUpRight size={14} /></button></section>; }
function Metric({ icon: Icon, label, value, accent }) { const displayValue = typeof value === "number" ? value.toLocaleString() : String(value ?? "0"); return <div className="metric-card"><div className={`metric-icon ${accent}`}><Icon size={18} /></div><div><strong>{displayValue}</strong><span>{label}</span></div><small>LIVE</small></div>; }
function ActionCard({ icon: Icon, title, copy, onClick, tone }) { return <button className="action-card" onClick={onClick}><span className={`action-icon ${tone}`}><Icon size={21} /></span><span className="action-copy"><b>{title}</b><small>{copy}</small></span><ArrowUpRight size={18} /></button>; }
function SectionHeading({ eyebrow, title, action }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action}</div>; }
function PremiumCard({ user }) { return <section className={`premium-card ${user?.premium ? "is-active" : ""}`}><div className="premium-copy"><span className="pill"><Sparkles size={13} />{user?.premium ? "PREMIUM ACTIVE" : "PREMIUM ACCESS"}</span><h2>{user?.premium ? "Your workspace is fully unlocked." : "More uploads. Less friction."}</h2><p>{user?.premium ? "Keep publishing without free account and network quota limits." : "Join the Discord server to activate Premium and remove daily publishing limits."}</p><a className="button button-warm" href="https://discord.gg/pgsZDFTpWE" target="_blank" rel="noreferrer">{user?.premium ? "Premium active" : "Explore Premium"}<ArrowUpRight size={16} /></a></div><div className="premium-points"><div><b>01</b><span><strong>Unlimited uploads</strong><small>No daily file quota.</small></span></div><div><b>02</b><span><strong>Clean workflow</strong><small>One workspace for every asset.</small></span></div><div><b>03</b><span><strong>Priority access</strong><small>Built for creator teams.</small></span></div></div></section>; }
function Team() { const members = [{ name: "ZaneXyuu Studio", role: "Creative Director", focus: "Brand · Product direction", initials: "ZX", href: "https://www.roblox.com/users/8901376874/profile" }, { name: "Web Designer", role: "UI / UX Designer", focus: "Visual system · Motion", initials: "WD", href: "https://www.roblox.com/users/3107263049/profile" }, { name: "Backend Engineer", role: "Roblox API Developer", focus: "Open Cloud · Operations", initials: "BE", href: "https://www.roblox.com/users/8560821826/profile" }]; return <div className="view-stack"><section className="page-title"><div><p className="eyebrow">THE PEOPLE BEHIND THE BUILD</p><h1>Developer team<span>.</span></h1><p className="lead">A small team shaping a clearer way to move Roblox assets from idea to publish.</p></div></section><div className="team-grid">{members.map(member => <a className="member-card" key={member.name} href={member.href} target="_blank" rel="noreferrer"><span className="member-avatar">{member.initials}</span><span><b>{member.name}</b><strong>{member.role}</strong><small>{member.focus}</small></span><ArrowUpRight size={17} /></a>)}</div><section className="team-footer"><ShieldCheck size={22} /><div><b>Built around a safer publishing workflow.</b><p>Your credentials are handled by the Railway backend and are never stored in the browser history.</p></div></section></div>; }
